# CDW_SAPP_D_BRANCH

SELECT BRANCH_CODE, BRANCH_NAME, BRANCH_STREET, BRANCH_CITY, 
	   BRANCH_STATE, IF(BRANCH_ZIP = NULL, 999999, BRANCH_ZIP) AS BRANCH_ZIP, CONCAT('(',SUBSTRING(BRANCH_PHONE, 1, 3), ')' , 
																	   SUBSTRING(BRANCH_PHONE, 4, 3), '-' , 
																	   SUBSTRING(BRANCH_PHONE, 7, 4)) AS PHONE_NUMBER, LAST_UPDATED
FROM CDW_SAPP_BRANCH;

       
       
       
# CDW_SAPP_F_CREDITCARD       
       
SELECT TRANSACTION_ID, CREDIT_CARD_NO, CUST_SSN, DATE_FORMAT(CONCAT(year, '-', month, '-', day), GET_FORMAT(DATE, 'INTERNAL')) AS TIMEID, BRANCH_CODE, TRANSACTION_TYPE, TRANSACTION_VALUE, LAST_UPDATED
FROM CDW_SAPP_CREDITCARD;





# CDW_SAPP_TIME

SELECT DATE_FORMAT(CONCAT(year, '-', month, '-', day), GET_FORMAT(DATE, 'INTERNAL')) AS TIME_KEY, MONTH, DAY, YEAR, QUARTER(concat(year, '-', month, '-', day)), LAST_UPDATED
FROM CDW_SAPP_CREDITCARD;





# CDW_SAPP_CUSTOMER

SELECT SSN, CONCAT(UPPER(SUBSTRING(FIRST_NAME, 1,1)), LOWER(SUBSTRING(FIRST_NAME, 2))) AS FIRST_NAME, LOWER(MIDDLE_NAME) AS MIDDLE_NAME,
		    CONCAT(UPPER(SUBSTRING(LAST_NAME, 1, 1)), LOWER(SUBSTRING(LAST_NAME, 2))) LAST_NAME, CREDIT_CARD_NO, STREET_NAME, CUST_CITY, CUST_STATE, 	
            CUST_COUNTRY, CONVERT(CUST_ZIP, UNSIGNED INTEGER) AS CUST_ZIP, CONCAT(LEFT(CUST_PHONE,3), '-' , RIGHT(CUST_PHONE,4)) AS CUST_PHONE, 
            CUST_EMAIL, LAST_UPDATED

FROM CDW_SAPP_CUSTOMER;